### ISSUE TITLE
Update part of CRUD not working due to error

### ISSUE THREAD

**Issue by D-Stukes** [Lady-D/LadyD_Apothecary_Reference_Boutique#1]
Expectation:   Form rendered and item updated successfully after data is entered.

Actual Results: Form rendered but error received instead of update.

Actions taken to attempt to troubleshoot: checked the syntax of my edit.ejs file to ensure there are no typos.  Checked rest of piping (routers, controllers, etc.) to see if there were any syntax errors there.  Ran two tests in postman, first in the form option, second in the url option, both using put and completing body info needed for editing (keys and values.) Rec'd two different errors.  Cleared one - "category_id"was misspelled, however I didn't discover any problem with "product_name".

Error: "/Users/student_23/wdi/unit02/projects/ladyd_boutique/controllers/viewController.js:36
  editOneProducts
  ^
ReferenceError: editOneProducts is not defined
    at Object.<anonymous> (/Users/student_23/wdi/unit02/projects/ladyd_boutique/controllers/viewController.js:36:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/student_23/wdi/unit02/projects/ladyd_boutique/router/boutiqueRouter.js:3:32)
    at Module._compile (module.js:570:32)
[nodemon] app crashed - waiting for file changes before starting...
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
Listening on port 3000
{ id: '12' }
PUT /12 500 36.312 ms - 69
"

**Comment by Jon-zachary** [comment]
Hey Diane, It looks like you had your function editOneProduct misspelled. I checked your code and I can't find a 'editOneProducts' function so I'm not sure if you fixed it. If you're no longer getting that error please update the ticket. I'll be available to meet at around 1:15.
